version: "3.3"

services:
    redis:
      image: redis:alpine
      container_name: redis
      command: ["redis-server", "--appendonly", "yes"]
      ports:
        - 6379:6379
      volumes:
        - .dbdata-redis:/var/lib/redis